# 文件 3
# 文件类型：yaml
# 文件名称：frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/clamp-fyp-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: VITE_AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_AUTH_SERVICE_URL
                  name: frontend-env  # Changed from "-env" to "frontend-env"
            - name: VITE_COURSES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_COURSES_SERVICE_URL
                  name: frontend-env  # Changed from "-env" to "frontend-env"
            - name: VITE_FAVORITES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_FAVORITES_SERVICE_URL
                  name: frontend-env  # Changed from "-env" to "frontend-env"
            - name: VITE_INSTITUTES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_INSTITUTES_SERVICE_URL
                  name: frontend-env  # Changed from "-env" to "frontend-env"
            - name: VITE_RESOURCES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_RESOURCES_SERVICE_URL
                  name: frontend-env  # Changed from "-env" to "frontend-env"
            - name: VITE_SAVES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_SAVES_SERVICE_URL
                  name: frontend-env  # Changed from "-env" to "frontend-env"
          image: frontend:latest
          name: frontend
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 3000
              hostPort: 3001
              protocol: TCP
      restartPolicy: Always